// Code generated by sqlc. DO NOT EDIT.

package db

import (
	"database/sql"
)

type Account struct {
	ID           string
	Name         sql.NullString
	CreatedDate  sql.NullTime
	ModifiedDate sql.NullTime
}

type AccountBalance struct {
	ID       string
	Balance  sql.NullInt64
	Currency sql.NullString
}

type Currency struct {
	ID   string
	Desc sql.NullString
}

type PaymentData struct {
	ID             int32
	Debit          sql.NullInt64
	Credit         sql.NullInt64
	AccountID      sql.NullString
	LastBalance    sql.NullInt64
	CurrentBalance sql.NullInt64
	Direction      sql.NullString
	ToAccountID    sql.NullString
	FromAccountID  sql.NullString
}
